name: Release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Process Submissions
        env:
          CODEFORCES_USERNAME: ${{ secrets.CODEFORCES_USERNAME }}
          CODEFORCES_PASSWORD: ${{ secrets.CODEFORCES_PASSWORD }}
        run: |
          go run cmd/generate.go process
          git push origin main
          
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o codevault main.go
          mkdir release
          mv codevault release/codevault-${{ matrix.goos }}-${{ matrix.goarch }}
          
      - uses: softprops/action-gh-release@v1
        with:
          files: release/*